# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"
stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'Ramesh Seshadri(4a5542b7-1678-4c93-8575-6a46de726931)'
            subscriptionId: '4a5542b7-1678-4c93-8575-6a46de726931'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'RS-Sitecore-RG'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parameters.json'
            deploymentMode: 'Incremental'
            deploymentName: 'rssitecoredeploy'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Ramesh Seshadri(4a5542b7-1678-4c93-8575-6a46de726931)'
            ScriptType: 'InlineScript'
            Inline: |
            Install-Module Az.Resources -RequiredVersion 1.12.1-preview -AllowPrerelease -Force -Scope CurrentUser
            $Parameters = @{
            ResourcegroupName     = "RS-Sitecore-RG"
            Templatefile          = ".\StorageAccount\azuredeploy.json"
            TemplateParameterfile = ".\StorageAccount\azuredeploy.parameters.json"
            Mode                  = 'Incremental'
              }
            $Result = Get-AzResourceGroupDeploymentWhatIfResult @Parameters
            $Result
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true